//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolTourProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Activity
    {
        [Display(Name = "Activity ID")]
        
        public int ActivitiesID { get; set; }
        [RegularExpression(@"[A-Za-z\s]*", ErrorMessage = "Only letters and spaces are allowed")]
        [Required(ErrorMessage = "You did not enter an activity name")]
        [Display(Name = "What activity did you do?")]

        public string ActivityName { get; set; }

        [Display(Name = "Upload an image of the activity")]
        public byte[] Image { get; set; }

       // [Display(Name = "Enter your booking ID")]
       [Required(ErrorMessage ="You need to select your booking ID")]
        public int BookingID { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
